export const CATEGORIES = [
  "engineering",
  "testing",
  "infrastructure-devops",
  "security",
  "data",
  "ai",
  "design-ui",
  "art-creative",
  "media",
  "writing",
  "docs-productivity",
  "marketing-growth",
  "business-ops",
  "product",
  "communication",
  "research",
  "education",
  "integrations",
  "automation",
  "mobile",
  "games",
  "web3",
  "iot-hardware",
  "lifestyle",
] as const

export type Category = (typeof CATEGORIES)[number]

export function isCategory(value: string): value is Category {
  return (CATEGORIES as readonly string[]).includes(value)
}

const RAW_MAP: Record<string, Category> = {
  "developer tools": "engineering",
  developer: "engineering",
  engineering: "engineering",
  software: "engineering",
  dev: "engineering",
  coding: "engineering",
  testing: "testing",
  qa: "testing",
  test: "testing",
  quality: "testing",
  design: "design-ui",
  ui: "design-ui",
  ux: "design-ui",
  "design & ui": "design-ui",
  interface: "design-ui",
  "web design": "design-ui",
  "product design": "design-ui",
  writing: "writing",
  content: "writing",
  copywriting: "writing",
  blog: "writing",
  writing_content: "writing",
  data: "data",
  "data science": "data",
  analytics: "data",
  database: "data",
  sql: "data",
  research: "research",
  science: "research",
  academic: "research",
  marketing: "marketing-growth",
  growth: "marketing-growth",
  seo: "marketing-growth",
  advertising: "marketing-growth",
  ads: "marketing-growth",
  "social media": "marketing-growth",
  "demand gen": "marketing-growth",
  business: "business-ops",
  finance: "business-ops",
  legal: "business-ops",
  operations: "business-ops",
  hr: "business-ops",
  sales: "business-ops",
  ecommerce: "business-ops",
  productivity: "docs-productivity",
  documentation: "docs-productivity",
  docs: "docs-productivity",
  office: "docs-productivity",
  notes: "docs-productivity",
  security: "security",
  cybersecurity: "security",
  infosec: "security",
  appsec: "security",
  pentest: "security",
  media: "media",
  video: "media",
  audio: "media",
  music: "media",
  image: "media",
  photography: "media",
  "video production": "media",
  creative: "art-creative",
  art: "art-creative",
  illustration: "art-creative",
  graphics: "art-creative",
  "creative arts": "art-creative",
  devops: "infrastructure-devops",
  infrastructure: "infrastructure-devops",
  cloud: "infrastructure-devops",
  "platform engineering": "infrastructure-devops",
  sre: "infrastructure-devops",
  ai: "ai",
  "artificial intelligence": "ai",
  "machine learning": "ai",
  ml: "ai",
  llm: "ai",
  llms: "ai",
  agents: "ai",
  agent: "ai",
  "agent skills": "ai",
  "prompt engineering": "ai",
  mcp: "ai",
  product: "product",
  "product management": "product",
  roadmap: "product",
  pm: "product",
  communication: "communication",
  comms: "communication",
  email: "communication",
  outreach: "communication",
  education: "education",
  learning: "education",
  teaching: "education",
  integration: "integrations",
  integrations: "integrations",
  api: "integrations",
  connectors: "integrations",
  automation: "automation",
  workflow: "automation",
  rpa: "automation",
  scraping: "automation",
  mobile: "mobile",
  ios: "mobile",
  android: "mobile",
  game: "games",
  games: "games",
  gamedev: "games",
  "game development": "games",
  "game design": "games",
  unity: "games",
  godot: "games",
  web3: "web3",
  blockchain: "web3",
  crypto: "web3",
  "smart contracts": "web3",
  defi: "web3",
  iot: "iot-hardware",
  hardware: "iot-hardware",
  embedded: "iot-hardware",
  robotics: "iot-hardware",
  electronics: "iot-hardware",
  lifestyle: "lifestyle",
  travel: "lifestyle",
  health: "lifestyle",
  food: "lifestyle",
  personal: "lifestyle",
}

export function tryMapCategory(raw: string | undefined): Category | undefined {
  if (!raw) return undefined
  const key = raw.trim().toLowerCase()
  if (isCategory(key)) return key
  return RAW_MAP[key]
}

export function mapCategory(raw: string | undefined, fallback: Category = "engineering"): Category {
  return tryMapCategory(raw) ?? fallback
}

/** Domain-specific GitHub topic hints. Generic skill-collection topics (claude-skills, agent-skills, …) are deliberately absent so the classifier decides. */
export const TOPIC_HINTS: Record<string, Category> = {
  gamedev: "games",
  "game-development": "games",
  godot: "games",
  unity: "games",
  "game-engine": "games",
  "mobile-development": "mobile",
  "react-native": "mobile",
  flutter: "mobile",
  ios: "mobile",
  android: "mobile",
  blockchain: "web3",
  solidity: "web3",
  ethereum: "web3",
  defi: "web3",
  web3: "web3",
  "machine-learning": "ai",
  llm: "ai",
  "llm-agents": "ai",
  mcp: "ai",
  "ai-agents": "ai",
  rag: "ai",
  "prompt-engineering": "ai",
  seo: "marketing-growth",
  marketing: "marketing-growth",
  growth: "marketing-growth",
  "content-marketing": "marketing-growth",
  cybersecurity: "security",
  security: "security",
  pentest: "security",
  "data-science": "data",
  "data-engineering": "data",
  sql: "data",
  devops: "infrastructure-devops",
  kubernetes: "infrastructure-devops",
  terraform: "infrastructure-devops",
  "cloud-native": "infrastructure-devops",
  design: "design-ui",
  "ui-design": "design-ui",
  ux: "design-ui",
  figma: "design-ui",
  video: "media",
  audio: "media",
  music: "media",
  "video-editing": "media",
  writing: "writing",
  education: "education",
  tutorial: "education",
  testing: "testing",
  "test-automation": "testing",
  automation: "automation",
  scraping: "automation",
  "web-scraping": "automation",
  research: "research",
  robotics: "iot-hardware",
  embedded: "iot-hardware",
  arduino: "iot-hardware",
  esp32: "iot-hardware",
  "3d-printing": "iot-hardware",
  travel: "lifestyle",
  recipe: "lifestyle",
  fitness: "lifestyle",
}

/** Tie-break order when category scores are within one point: specialised domains first, engineering last. */
export const CATEGORY_PRIORITY: Category[] = [
  "security",
  "ai",
  "web3",
  "games",
  "mobile",
  "iot-hardware",
  "data",
  "infrastructure-devops",
  "testing",
  "design-ui",
  "art-creative",
  "media",
  "writing",
  "marketing-growth",
  "business-ops",
  "product",
  "communication",
  "research",
  "education",
  "integrations",
  "automation",
  "docs-productivity",
  "lifestyle",
  "engineering",
]

export function priorityRank(category: Category): number {
  const index = CATEGORY_PRIORITY.indexOf(category)
  return index === -1 ? CATEGORY_PRIORITY.length : index
}
